# Human readable title of application.
title: Crossplane Rook

overviewShort: The Rook Crossplane Stack enabling resource management for Rook.
overview: |-
  The Rook Crossplane Stack adds support for managing Rook resources from a Crossplane Kubernetes cluster.

  YugabyteDB and CockroachDB cluster resources can be provisioned, updated, and deleted by this stack.

# Markdown description of this entry
readme: |
 This `stack-rook` repository is the implementation of a Crossplane infrastructure
 [stack](https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-stacks.md) for
 [Rook](https://rook.io/).
 The stack that is built from the source code in this repository can be installed into a Crossplane control plane and adds the following new functionality:

 * Custom Resource Definitions (CRDs) that model Rook infrastructure and services (e.g. [Yugabyte](https://github.com/yugabyte/yugabyte-db), [CockroachDB](https://github.com/cockroachdb/cockroach), etc.)
 * Controllers to provision these resources in a Rook Kubernetes cluster based on the users desired state captured in CRDs they create
 * Implementations of Crossplane's [portable resource abstractions](https://crossplane.io/docs/master/running-resources.html), enabling Rook resources to fulfill a user's general need for cloud services

# Version of project (optional)
# If omitted the version will be filled with the docker tag
# If set it must match the docker tag
version: 0.0.1

# Maintainer names and emails.
maintainers:
- name: Jared Watts
  email: jared@upbound.io

# Owner names and emails.
owners:
- name: Jared Watts
  email: jared@upbound.io

# Human readable company name
company: Crossplane

# Keywords that describe this application and help search indexing
keywords:
- "rook"
- "infrastructure"

# Links to more information about the application (about page, source code, etc.)
website: "https://crossplane.io"
source: "https://github.com/crossplaneio/stack-rook"

# RBAC ClusterRoles will be generated permitting this stack to use all verbs on all
# resources in the groups listed below.
permissionScope: Cluster
dependsOn:
- crd: '*.cache.crossplane.io/v1alpha1'
- crd: '*.compute.crossplane.io/v1alpha1'
- crd: '*.database.crossplane.io/v1alpha1'
- crd: '*.kubernetes.crossplane.io/v1alpha1'
- crd: '*.core.crossplane.io/v1alpha1'
- crd: '*.storage.crossplane.io/v1alpha1'
- crd: '*.workload.crossplane.io/v1alpha1'

# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
